#!/usr/bin/env bash
set -euo pipefail

# Generate declarative mounts for attached internal IDE/SATA/NVMe filesystems.
#
# Usage:
#   ./nixos/scripts/generate-storage-config.sh /mnt
#
# The target root must be a separately mounted installation root, normally
# /mnt. The generated module uses filesystem UUIDs, so connector/device names
# such as /dev/sdb or /dev/nvme1n1 may change without breaking the mounts.

TARGET_ROOT="${1:-/mnt}"
TARGET_ROOT="${TARGET_ROOT%/}"
[[ -n "$TARGET_ROOT" ]] || TARGET_ROOT="/"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUTPUT="$REPO_ROOT/nixos/hosts/arch-desktop/storage-configuration.nix"
MOUNT_BASE="/mnt"

for cmd in lsblk jq mountpoint; do
  command -v "$cmd" >/dev/null || {
    echo "$cmd is required. The official NixOS installer includes it." >&2
    exit 1
  }
done

if [[ "$TARGET_ROOT" == "/" ]]; then
  echo "Refusing to scan through the live root filesystem (/)." >&2
  echo "Use a separately mounted installation root, normally /mnt." >&2
  exit 1
fi

if [[ ! -d "$TARGET_ROOT" ]]; then
  echo "Target root does not exist: $TARGET_ROOT" >&2
  exit 1
fi

if ! mountpoint -q "$TARGET_ROOT"; then
  echo "Target root is not a mount point: $TARGET_ROOT" >&2
  exit 1
fi

json="$(lsblk --json --bytes --output PATH,NAME,TYPE,TRAN,FSTYPE,UUID,LABEL,PARTTYPE,PARTLABEL,MOUNTPOINTS,SIZE)"

# Emit one TSV row per mountable filesystem. Transport is inherited from the
# parent disk because partitions do not consistently repeat TRAN in lsblk.
mapfile -t rows < <(
  jq -r --arg target "$TARGET_ROOT" '
    def nodes($transport):
      (.tran // $transport) as $t
      | { path, type, transport: $t, fstype, uuid, label, parttype,
          partlabel, mountpoints, size }
      , ((.children // [])[] | nodes($t));

    def mounted_under_target:
      (.mountpoints // [])
      | map(select(. != null and . != ""))
      | any(. == $target or startswith($target + "/"));

    def system_parttype:
      ((.parttype // "") | ascii_downcase) as $p
      | [
          "c12a7328-f81f-11d2-ba4b-00a0c93ec93b", # EFI System Partition
          "21686148-6449-6e6f-744e-656564454649", # BIOS boot
          "e3c9e316-0b5c-4db8-817d-f92df00215ae", # Microsoft reserved
          "de94bba4-06d1-4d40-a16a-bfd50179d6ac", # Windows recovery
          "0657fd6d-a4ab-43c4-84e5-0933c84b4f4f", # Linux swap
          "0x82",                                  # MBR Linux swap
          "0xef",                                  # MBR EFI
          "0x27"                                   # MBR Windows recovery
        ] | index($p) != null;

    def system_label:
      ((.label // "") + " " + (.partlabel // ""))
      | test("(^|[ _-])(efi|esp|recovery|msr|system[ _-]*reserved|bios[ _-]*boot)([ _-]|$)"; "i");

    def mountable_fs:
      .fstype as $f
      | ["ext2","ext3","ext4","btrfs","xfs","f2fs","ntfs","exfat","vfat","bcachefs"]
      | index($f) != null;

    .blockdevices[]
    | nodes(null)
    | select(.type == "part" or .type == "disk")
    | select((.transport // "") | test("^(ata|sata|ide|nvme)$"; "i"))
    | select(.uuid != null and .uuid != "")
    | select(.fstype != null and .fstype != "")
    | select(mountable_fs)
    | select(mounted_under_target | not)
    | select(system_parttype | not)
    | select(system_label | not)
    # A small FAT filesystem on an internal disk is overwhelmingly likely to
    # be firmware/boot plumbing. Skip it rather than mounting it as user data.
    | select((.fstype != "vfat") or ((.size // 0) >= 4294967296))
    | [ .path, .fstype, .uuid, (.label // "__NIXOS_AUTOMOUNT_NO_LABEL__") ]
    | @tsv
  ' <<<"$json"
)

sanitize_name() {
  local value="$1"
  # Stable, path-safe ASCII name. Labels are only for human-readable paths;
  # the actual mount identity is always the filesystem UUID.
  value="$(printf '%s' "$value" | tr ' ' '-' | sed -E 's/[^A-Za-z0-9._-]+/-/g; s/^-+//; s/-+$//; s/-+/-/g')"
  printf '%s' "${value:-disk}"
}

mkdir -p "$(dirname "$OUTPUT")"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

cat >"$tmp" <<'NIX'
# AUTO-GENERATED by nixos/scripts/generate-storage-config.sh.
# Re-run that script rather than editing this file by hand.
#
# Internal data filesystems are addressed by UUID and lazy-mounted on first
# access. "nofail" means a missing/offline disk never blocks boot.
{ ... }:
{
NIX

declare -A used_names=()
count=0

for row in "${rows[@]}"; do
  IFS=$'\t' read -r dev fstype uuid label <<<"$row"
  [[ "$label" == "__NIXOS_AUTOMOUNT_NO_LABEL__" ]] && label=""

  short_uuid="${uuid//-/}"
  short_uuid="${short_uuid:0:8}"
  if [[ -n "$label" ]]; then
    name="$(sanitize_name "$label")"
  else
    name="disk-$short_uuid"
  fi

  if [[ -n "${used_names[$name]:-}" ]]; then
    name="$name-$short_uuid"
  fi
  used_names[$name]=1

  mountpoint="$MOUNT_BASE/$name"
  nix_fstype="$fstype"
  [[ "$nix_fstype" == "ntfs" ]] && nix_fstype="ntfs3"

  options=(
    '"nofail"'
    '"x-systemd.automount"'
    '"x-systemd.device-timeout=5s"'
    '"x-gvfs-show"'
  )

  # FAT/exFAT/NTFS do not store normal Unix ownership. Make them writable by
  # filken (UID 1000, pinned in base.nix) while leaving native Linux filesystems
  # to preserve their on-disk ownership and permissions.
  case "$nix_fstype" in
    ntfs3|exfat|vfat)
      options+=( '"uid=1000"' '"gid=100"' '"umask=0022"' )
      ;;
  esac

  {
    printf '  fileSystems."%s" = {\n' "$mountpoint"
    printf '    device = "/dev/disk/by-uuid/%s";\n' "$uuid"
    printf '    fsType = "%s";\n' "$nix_fstype"
    printf '    options = [ %s ];\n' "${options[*]}"
    printf '  };\n\n'
  } >>"$tmp"

  printf '  %-18s %-8s %-38s -> %s\n' "$dev" "$nix_fstype" "$uuid" "$mountpoint"
  count=$((count + 1))
done

cat >>"$tmp" <<'NIX'
}
NIX

mv "$tmp" "$OUTPUT"
trap - EXIT

echo
if (( count == 0 )); then
  echo "No additional internal data filesystems detected."
else
  echo "Generated $OUTPUT with $count internal data filesystem(s)."
fi
