separator=true
separator_block_width=12

[cpu]
command=printf 'CPU '; grep 'cpu ' /proc/stat | awk '{u=$2+$4; t=$2+$4+$5; if (p>0) printf "%.0f%%\\n", (u-pu)*100/(t-p); else print "..."; pu=u; p=t}'
interval=5

[memory]
command=free -m | awk '/Mem:/ {printf "MEM %.0f%%\\n", $3*100/$2}'
interval=5

[power]
command=~/.config/i3/scripts/ppd-status
interval=5

[time]
command=date '+%a %Y-%m-%d %H:%M'
interval=30
